name: My first GitHub workflow
run-name: First workflow # Optional
permissions: {}

# Events triggering the workflow
on: [push]

jobs:
  greet:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - run: echo "Hello world"

  checks:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: "Run checks"
        run: |
          echo "Run checks"
          sleep 20

  run-code:
    needs: checks
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    permissions:
      contents: read

    strategy:
      matrix:
        python-version: [ "3.12", "3.13", "3.14" ]
        os: [ "ubuntu-latest", "macos-latest", "windows-latest" ]
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - run: python mycode.py

      - name: Extra step for Python 3.14
        if: ${{ matrix.python-version == '3.14' }}
        run: echo "Extra step for Python 3.14"

      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements-dev.txt

      - name: Run tests
        run: pytest